# Generated by Django 5.2.1 on 2025-05-15 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('LIGHT', 'Light'), ('MOTOR', 'Motor'), ('THERMOSTAT', 'Thermostat')], default='LIGHT', max_length=50)),
                ('pin', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='iotapp.room')),
            ],
        ),
    ]
