# Generated by Django 5.2.1 on 2025-05-16 00:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='pin',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='ComponentData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ON', 'On'), ('OFF', 'Off'), ('TOGGLE', 'Toggle'), ('READ', 'Read')], default='OFF', max_length=50)),
                ('mode', models.CharField(choices=[('AUTO', 'Auto'), ('MANUAL', 'Manual'), ('SCHEDULE', 'Schedule')], default='AUTO', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_value', models.CharField(blank=True, max_length=50, null=True)),
                ('current_value', models.CharField(blank=True, max_length=50, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='iotapp.component')),
            ],
        ),
    ]
