# Generated by Django 5.2.1 on 2025-05-17 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotapp', '0002_alter_component_pin_alter_room_name_componentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='arduiono_id',
            field=models.IntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='type',
            field=models.CharField(choices=[('LED', 'led'), ('MOTOR', 'motor'), ('DTH', 'dth'), ('LDR', 'ldr'), ('PIR', 'pir')], default='LED', max_length=50),
        ),
        migrations.AlterField(
            model_name='componentdata',
            name='action',
            field=models.CharField(choices=[('ON', 'on'), ('OFF', 'off'), ('TOGGLE', 'toggle'), ('READ', 'read')], default='OFF', max_length=50),
        ),
        migrations.AlterField(
            model_name='componentdata',
            name='mode',
            field=models.CharField(choices=[('AUTO', 'auto'), ('MANUAL', 'manual'), ('SCHEDULE', 'schedule')], default='AUTO', max_length=50),
        ),
    ]
