# Generated by Django 5.2.1 on 2025-05-17 21:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotapp', '0003_room_arduiono_id_alter_component_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='pin',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='component',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotapp.room'),
        ),
        migrations.AlterField(
            model_name='component',
            name='type',
            field=models.CharField(choices=[('led', 'led'), ('motor', 'motor'), ('dth', 'dth'), ('ldr', 'ldr'), ('pir', 'pir')], max_length=50),
        ),
        migrations.AlterField(
            model_name='componentdata',
            name='action',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off'), ('toggle', 'toggle'), ('read', 'read')], default='off', max_length=50),
        ),
        migrations.AlterField(
            model_name='componentdata',
            name='mode',
            field=models.CharField(choices=[('auto', 'auto'), ('manual', 'manual'), ('backend', 'backend')], default='auto', max_length=50),
        ),
    ]
