# Generated by Django 5.2.1 on 2025-05-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotapp', '0005_alter_component_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentdata',
            name='current_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='componentdata',
            name='previous_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
