# Generated by Django 5.2.1 on 2025-05-19 00:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotapp', '0006_alter_componentdata_current_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='mode',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='componentdata',
            name='action',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off'), ('toggle', 'toggle'), ('read', 'read'), ('set', 'set')], default='off', max_length=50),
        ),
        migrations.AlterField(
            model_name='componentdata',
            name='current_value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
