# Generated by Django 5.2.1 on 2025-05-19 02:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotapp', '0008_alter_component_pin_alter_component_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='pin',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='component',
            name='type',
            field=models.CharField(choices=[('led', 'led'), ('motor', 'motor'), ('dht', 'dht'), ('ldr', 'ldr'), ('pir', 'pir')], max_length=50),
        ),
    ]
