# Generated by Django 5.2.1 on 2025-05-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotapp', '0010_alter_component_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='type',
            field=models.CharField(blank=True, choices=[('led', 'led'), ('motor', 'motor'), ('dht', 'dht'), ('dht_humidity', 'dht_humidity'), ('ldr', 'ldr'), ('pir', 'pir')], max_length=50, null=True),
        ),
    ]
